nvbach91/4IZ278-2023-2024-LS

www/zedm00/cv01/css/main.css
www/zedm00/cv01/index.php

projekt na eso vše: https://eso.vse.cz/~zedm00/cv01/

zedm00-cv01

---

www/davj05/cv01/css/main.css
www/davj05/cv01/index.php

Odevzdání úkolu 1 - https://eso.vse.cz/~davj05/cv01/

davj05-cv01

---

www/hlas03/cv01/css/main.css
www/hlas03/cv01/index.php

Odevzdavam cviceni 01
https://eso.vse.cz/~hlas03/cv01/

hlas03-cv01

---

www/fanm02/cv01/index.php

Odevzdávám svou vizitku
https://eso.vse.cz/~fanm02/cv01/

fanm02-cv01

---

www/boxd00/cv01/index.php
www/boxd00/cv01/static/style.css

Odevzdávám cvičení 01
https://eso.vse.cz/~boxd00/cv01/

boxd00-cv01

---

www/lacp06/cv01/css.css
www/lacp06/cv01/index.php

Odevzdávám cvičení 01
Odkaz: https://eso.vse.cz/~lacp06/cv01/

lacp06-cv01

---

www/davj05/cv02/classes/Person.php
www/davj05/cv02/components/cards.php
www/davj05/cv02/css/main.css
www/davj05/cv02/includes/head.php
www/davj05/cv02/index.php

Odevzdání úkolu 2
https://eso.vse.cz/~davj05/cv02/

davj05-cv02

---

www/auza00/cv02/classes/Person.php
www/auza00/cv02/css/main.css
www/auza00/cv02/index.php

úkol č.2
odkaz: https://eso.vse.cz/~auza00/cv02/

auza00-cv02

---

www/lean04/cv02/classes/Address.php
www/lean04/cv02/classes/Company.php
www/lean04/cv02/classes/Person.php
www/lean04/cv02/classes/Worker.php
www/lean04/cv02/components/businessCard.php
www/lean04/cv02/components/businessCards.php
www/lean04/cv02/css/main.css
www/lean04/cv02/includes/foot.php
www/lean04/cv02/includes/head.php
www/lean04/cv02/index.php

Odkaz na práce na serveru eso je https://eso.vse.cz/~lean04/cv02/

lean04-cv02

---

www/auza00/cv03/index.php

odezvdávám úkol č.3
https://eso.vse.cz/~auza00/cv03/

auza00-cv03

---

www/chav07/cv03/components/registrationForm.php
www/chav07/cv03/includes/bottom.php
www/chav07/cv03/includes/top.php
www/chav07/cv03/index.php
www/chav07/cv03/main.css

Odevzdání úkolu ze cv03.
https://eso.vse.cz/~chav07/cv03/

chav07-cv03

---

www/brud06/cv03/css/style.css
www/brud06/cv03/includes/foot.php
www/brud06/cv03/includes/head.php
www/brud06/cv03/index.php

Dobrý den,
odevzdávám úkol lab03:
https://eso.vse.cz/~brud06/cv03/

brud06-cv03

---

www/nikd01/cv03/css/style.css
www/nikd01/cv03/includes/foot.php
www/nikd01/cv03/includes/head.php
www/nikd01/cv03/index.php

https://eso.vse.cz/~nikd01/cv03/

nikd01-cv03

---

www/talp03/cv03/css/style.css
www/talp03/cv03/index.php

https://eso.vse.cz/~talp03/cv03/

talp03-cv03

---

www/kouv13/cv03/components/app.php
www/kouv13/cv03/components/body.php
www/kouv13/cv03/components/head.php
www/kouv13/cv03/index.php

odevzdavám ukol na cv03: https://eso.vse.cz/~kouv13/cv03/

kouv13-cv03

---

www/adad05/cv03/components/main.php
www/adad05/cv03/css/main.css
www/adad05/cv03/includes/footer.php
www/adad05/cv03/includes/head.php
www/adad05/cv03/index.php

Odevzdávám třetí domácí úkol.
Adresa na školním serveru: https://eso.vse.cz/~adad05/cv03/

adad05-cv03

---

www/pycd01/cv03/index.php
www/pycd01/cv03/styles/style.css

https://eso.vse.cz/~pycd01/cv03/

pycd01-cv03

---

www/fanm02/cv03/components/footer.php
www/fanm02/cv03/components/header.php
www/fanm02/cv03/index.php
www/fanm02/cv03/styles/style.css

https://eso.vse.cz/~fanm02/cv03/index.php

fanm02-cv03

---

www/pycd01/cv04/admin/users.php
www/pycd01/cv04/index.php
www/pycd01/cv04/login.php
www/pycd01/cv04/register.php
www/pycd01/cv04/styles/form.css
www/pycd01/cv04/styles/style.css
www/pycd01/cv04/users.db
www/pycd01/cv04/utils/userUtils.php

https://eso.vse.cz/~pycd01/cv04/

pycd01-cv04

---

www/brud06/cv04/admin/users.php
www/brud06/cv04/css/style.css
www/brud06/cv04/css/users.css
www/brud06/cv04/includes/foot.php
www/brud06/cv04/includes/head.php
www/brud06/cv04/index.php
www/brud06/cv04/login.php
www/brud06/cv04/registration.php
www/brud06/cv04/users.db
www/brud06/cv04/utils/utils.php

Dobrý den,
Odevzdávám úkol LAB04:
https://eso.vse.cz/~brud06/cv04/

brud06-cv04

---

www/talp03/cv04/css/home.css
www/talp03/cv04/css/style.css
www/talp03/cv04/css/users.css
www/talp03/cv04/home.php
www/talp03/cv04/index.php
www/talp03/cv04/login.php
www/talp03/cv04/users.php
www/talp03/cv04/users.text
www/talp03/cv04/utils.php

https://eso.vse.cz/~talp03/cv04/

talp03-cv04

---

www/kouv13/cv04/admin/users.php
www/kouv13/cv04/components/app.php
www/kouv13/cv04/components/auth.php
www/kouv13/cv04/components/head.php
www/kouv13/cv04/components/loginBody.php
www/kouv13/cv04/components/registrationBody.php
www/kouv13/cv04/components/utils.php
www/kouv13/cv04/index.php
www/kouv13/cv04/login.php
www/kouv13/cv04/registration.php
www/kouv13/cv04/users.db

Odevzdávám úkol z cv04: https://eso.vse.cz/~kouv13/cv04/registration.php

kouv13-cv04

---

www/hlas03/cv04/admin/users.php
www/hlas03/cv04/css/main.css
www/hlas03/cv04/login.php
www/hlas03/cv04/registration.php
www/hlas03/cv04/users.db
www/hlas03/cv04/utils/utils.php

odevzdavam cviceni 04
https://eso.vse.cz/~hlas03/cv04/registration.php

hlas03-cv04

---

www/fanm02/cv04/admin/users.php
www/fanm02/cv04/components/footer.php
www/fanm02/cv04/components/header.php
www/fanm02/cv04/index.php
www/fanm02/cv04/login.php
www/fanm02/cv04/registration.php
www/fanm02/cv04/styles/style.css
www/fanm02/cv04/utils/utils.php

https://eso.vse.cz/~fanm02/cv04/

fanm02-cv04

---

www/lean04/cv04/admin.php
www/lean04/cv04/css/main.css
www/lean04/cv04/includes/footer.php
www/lean04/cv04/includes/head.php
www/lean04/cv04/includes/header.php
www/lean04/cv04/includes/loginForm.php
www/lean04/cv04/includes/registrationForm.php
www/lean04/cv04/includes/users.php
www/lean04/cv04/index.php
www/lean04/cv04/login.php
www/lean04/cv04/registration.php
www/lean04/cv04/utils/fs.php
www/lean04/cv04/utils/navigation.php
www/lean04/cv04/utils/users.php

Odkaz na práce na serveru eso je https://eso.vse.cz/~lean04/cv04/

lean04-cv04

---

www/adad05/cv04/components/login.php
www/adad05/cv04/components/main.php
www/adad05/cv04/components/registration.php
www/adad05/cv04/components/users.php
www/adad05/cv04/components/utils.php
www/adad05/cv04/css/main.css
www/adad05/cv04/includes/footer.php
www/adad05/cv04/includes/head.php
www/adad05/cv04/index.php
www/adad05/cv04/login/css/main.css
www/adad05/cv04/login/index.php
www/adad05/cv04/registration/css/main.css
www/adad05/cv04/registration/index.php
www/adad05/cv04/users.txt
www/adad05/cv04/users/css/main.css
www/adad05/cv04/users/index.php

Dobrý večer, odevzdávám úkol 4.
Zde je odkaz na eso: https://eso.vse.cz/~adad05/cv04/
Pěkný večer.
Daniel Adam

adad05-cv04

---

www/nikd01/cv04/admin/users.php
www/nikd01/cv04/css/style.css
www/nikd01/cv04/database/users.db
www/nikd01/cv04/includes/foot.php
www/nikd01/cv04/includes/head.php
www/nikd01/cv04/index.php
www/nikd01/cv04/login.php
www/nikd01/cv04/utils/utils.php

https://eso.vse.cz/~nikd01/cv04/

nikd01-cv04

---

www/kouv13/cv05/db.php
www/kouv13/cv05/index.php

odevzdavam ukol na cv05
https://eso.vse.cz/~kouv13/cv05/

kouv13-cv05

---

www/adad05/cv05/classes/Database.php
www/adad05/cv05/classes/DatabaseConnection.php
www/adad05/cv05/classes/DatabaseOperations.php
www/adad05/cv05/classes/MatchesDB.php
www/adad05/cv05/classes/PlayersDB.php
www/adad05/cv05/classes/TeamsDB.php
www/adad05/cv05/index.php

Dobrý den,
odevzdávám práci č. 5, zde je odkaz na eso: https://eso.vse.cz/~adad05/cv05/
Přeji pěkný večer.

adad05-cv05

---

www/lukt03/cv05/.gitignore
www/lukt03/cv05/database-config.example.php
www/lukt03/cv05/database.php
www/lukt03/cv05/index.php

https://eso.vse.cz/~lukt03/cv05/

lukt03-cv05

---

www/lean04/cv05/database.php
www/lean04/cv05/index.php

Odkaz na práce na serveru eso je https://eso.vse.cz/~lean04/cv05/

lean04-cv05

---

www/pycd01/cv05/classes/Matches.php
www/pycd01/cv05/classes/Players.php
www/pycd01/cv05/classes/Teams.php
www/pycd01/cv05/classes/Users.php
www/pycd01/cv05/index.php
www/pycd01/cv05/utils/db.php

https://eso.vse.cz/~pycd01/cv05/

pycd01-cv05

---

www/fanm02/cv05/components/db_test.php
www/fanm02/cv05/components/footer.php
www/fanm02/cv05/components/header.php
www/fanm02/cv05/db/matches.php
www/fanm02/cv05/db/players.php
www/fanm02/cv05/db/teams.php
www/fanm02/cv05/index.php
www/fanm02/cv05/styles/style.css
www/fanm02/cv05/utils/db.php

https://eso.vse.cz/~fanm02/cv05/

fanm02-cv05

---

www/lukt03/cv06/components/CategoryDisplay.php
www/lukt03/cv06/components/ProductDisplay.php
www/lukt03/cv06/components/SlideDisplay.php
www/lukt03/cv06/config/.gitignore
www/lukt03/cv06/config/config.example.php
www/lukt03/cv06/css/mystyles.css
www/lukt03/cv06/css/styles.css
www/lukt03/cv06/db/CategoriesDB.php
www/lukt03/cv06/db/Database.php
www/lukt03/cv06/db/DatabaseConnection.php
www/lukt03/cv06/db/DatabaseOperations.php
www/lukt03/cv06/db/ProductsDB.php
www/lukt03/cv06/db/SlidesDB.php
www/lukt03/cv06/includes/foot.php
www/lukt03/cv06/includes/head.php
www/lukt03/cv06/index.php

https://eso.vse.cz/~lukt03/cv06/

lukt03-cv06

---

www/fanm02/cv06/components/CategoryDisplay.php
www/fanm02/cv06/components/ProductDisplay.php
www/fanm02/cv06/components/SlideDisplay.php
www/fanm02/cv06/db/CategoryDB.php
www/fanm02/cv06/db/ProductDB.php
www/fanm02/cv06/db/SlideDB.php
www/fanm02/cv06/index.php
www/fanm02/cv06/style/styles.css
www/fanm02/cv06/utils/db.php

https://eso.vse.cz/~fanm02/cv06/

fanm02-cv06

---

www/lacp06/cv06/db/database_eshop.php
www/lacp06/cv06/db/db_eshop.php
www/lacp06/cv06/includes/CategoryDisplay.php
www/lacp06/cv06/includes/ProductDisplay.php
www/lacp06/cv06/includes/SlideDisplay.php
www/lacp06/cv06/index.php
www/lacp06/cv06/styles.css

Odevzdávám úkol cv06
https://eso.vse.cz/~lacp06/cv06/

lacp06-cv06

---

www/pycd01/cv06/classes/Categories.php
www/pycd01/cv06/classes/Products.php
www/pycd01/cv06/classes/Users.php
www/pycd01/cv06/index.php
www/pycd01/cv06/style.css
www/pycd01/cv06/utils/db.php

https://eso.vse.cz/~pycd01/cv06/

pycd01-cv06

---

www/lean04/cv06/components/CategoryDisplay.php
www/lean04/cv06/components/ProductDisplay.php
www/lean04/cv06/components/SlideDisplay.php
www/lean04/cv06/css/styles.css
www/lean04/cv06/database/CategoriesDB.php
www/lean04/cv06/database/Database.php
www/lean04/cv06/database/ProductsDB.php
www/lean04/cv06/database/SlidesDB.php
www/lean04/cv06/index.php

Odkaz na práce na serveru eso je https://eso.vse.cz/~lean04/cv06/

lean04-cv06

---

www/adad05/cv06/classes/CategoriesDB.php
www/adad05/cv06/classes/Database.php
www/adad05/cv06/classes/DatabaseConnection.php
www/adad05/cv06/classes/DatabaseOperations.php
www/adad05/cv06/classes/ProductsDB.php
www/adad05/cv06/classes/SlidesDB.php
www/adad05/cv06/components/CategoryDisplay.php
www/adad05/cv06/components/ProductDisplay.php
www/adad05/cv06/components/SlideDisplay.php
www/adad05/cv06/components/body.php
www/adad05/cv06/css/styles.css
www/adad05/cv06/includes/head.php
www/adad05/cv06/index.php

Dobrý den, odevzdávám domácí úkol 6.
Zde je odkaz na eso: https://eso.vse.cz/~adad05/cv06/

adad05-cv06

---

www/hlas03/cv05/database-constants.php
www/hlas03/cv05/database.php
www/hlas03/cv05/index.php

odevzdavam cviceni 05 
https://eso.vse.cz/~hlas03/cv05/

hlas03-cv05

---

www/jana19/cv06/components/CategoryDisplay.php
www/jana19/cv06/components/ProductDisplay.php
www/jana19/cv06/components/SlideDisplay.php
www/jana19/cv06/config/constant.php
www/jana19/cv06/css/styles.css
www/jana19/cv06/db/CategoriesDB.php
www/jana19/cv06/db/Database.php
www/jana19/cv06/db/DatabaseConnection.php
www/jana19/cv06/db/DatabaseOperations.php
www/jana19/cv06/db/ProductsDB.php
www/jana19/cv06/db/SlidesDB.php
www/jana19/cv06/includes/footer.php
www/jana19/cv06/includes/header.php
www/jana19/cv06/index.html
www/jana19/cv06/index.php

práce za cv06
https://eso.vse.cz/~jana19/cv06/index.php

jana19-cv06

---

www/talp03/cv06/classes/CategoryDB.php
www/talp03/cv06/classes/ProductsDB.php
www/talp03/cv06/css/styles.css
www/talp03/cv06/includes/category.php
www/talp03/cv06/includes/footer.php
www/talp03/cv06/includes/head.php
www/talp03/cv06/includes/navigation.php
www/talp03/cv06/includes/products.php
www/talp03/cv06/index.php
www/talp03/cv06/utils/database.php

Dobrý den, opožděně odevzdávám úkol ze cvičení 6
https://eso.vse.cz/~talp03/cv06/

talp03-cv06

---

www/mald16/cv08/buy.php
www/mald16/cv08/cart.php
www/mald16/cv08/create-item.php
www/mald16/cv08/css/custom-styles.css
www/mald16/cv08/css/styles.css
www/mald16/cv08/db/db.php
www/mald16/cv08/delete-item.php
www/mald16/cv08/edit-item.php
www/mald16/cv08/inc/foot.php
www/mald16/cv08/inc/head.php
www/mald16/cv08/index.php
www/mald16/cv08/login.php
www/mald16/cv08/logout.php
www/mald16/cv08/remove-item.php

Posílám úkol ze cv08: https://eso.vse.cz/~mald16/cv08/

mald16-cv08

---

www/brud06/cv08/buy.php
www/brud06/cv08/cart.php
www/brud06/cv08/components/GoodsDisplay.php
www/brud06/cv08/create-item.php
www/brud06/cv08/css/myStyle.css
www/brud06/cv08/db/GoodsDB.php
www/brud06/cv08/db/database.php
www/brud06/cv08/delete-item.php
www/brud06/cv08/edit-item.php
www/brud06/cv08/includes/footer.php
www/brud06/cv08/includes/header.php
www/brud06/cv08/index.php
www/brud06/cv08/login.php
www/brud06/cv08/logout.php
www/brud06/cv08/remove-item.php

Dobrý den,
Odevzdávám domácí úkol LAB08
https://eso.vse.cz/~brud06/cv08/

brud06-cv08

---

www/lacp06/cv08/buy.php
www/lacp06/cv08/cart.php
www/lacp06/cv08/create-item.php
www/lacp06/cv08/db/database_eshop.php
www/lacp06/cv08/db/db_eshop.php
www/lacp06/cv08/delete-item.php
www/lacp06/cv08/edit-item.php
www/lacp06/cv08/includes/Footer.php
www/lacp06/cv08/includes/Header.php
www/lacp06/cv08/includes/ProductDisplay.php
www/lacp06/cv08/index.php
www/lacp06/cv08/login.php
www/lacp06/cv08/logout.php
www/lacp06/cv08/remove-item.php
www/lacp06/cv08/styles.css

Odevzdávám cv08
https://eso.vse.cz/~lacp06/cv08/index.php

lacp06-cv08

---

www/adad05/cv08/buy.php
www/adad05/cv08/cart.php
www/adad05/cv08/classes/Database.php
www/adad05/cv08/classes/DatabaseConnection.php
www/adad05/cv08/classes/DatabaseOperations.php
www/adad05/cv08/classes/GoodsDB.php
www/adad05/cv08/components/body.php
www/adad05/cv08/components/tabs.php
www/adad05/cv08/create-item.php
www/adad05/cv08/css/styles.css
www/adad05/cv08/delete-item.php
www/adad05/cv08/edit-item.php
www/adad05/cv08/includes/footer.php
www/adad05/cv08/includes/head.php
www/adad05/cv08/index.php
www/adad05/cv08/login.php
www/adad05/cv08/logout.php
www/adad05/cv08/remove-item.php

Dobrý večer, odevzdávám úkol ze cv08.
Zde je link na eso: https://eso.vse.cz/~adad05/cv08/

adad05-cv08

---

www/lean04/cv08/auth/logout.php
www/lean04/cv08/cart.php
www/lean04/cv08/components/LoginForm.php
www/lean04/cv08/components/ProductDisplay.php
www/lean04/cv08/components/ProductForm.php
www/lean04/cv08/create-item.php
www/lean04/cv08/css/bootstrap.css
www/lean04/cv08/css/styles.css
www/lean04/cv08/database/Database.php
www/lean04/cv08/database/ProductsDB.php
www/lean04/cv08/edit-item.php
www/lean04/cv08/includes/footer.php
www/lean04/cv08/includes/header.php
www/lean04/cv08/index.php
www/lean04/cv08/login.php
www/lean04/cv08/products/buy.php
www/lean04/cv08/products/delete-item.php
www/lean04/cv08/products/remove-item.php

Odkaz na práce na serveru eso je https://eso.vse.cz/~lean04/cv08/

lean04-cv08

---

www/jana19/cv08/buy.php
www/jana19/cv08/cart.php
www/jana19/cv08/components/CategoryDisplay.php
www/jana19/cv08/components/ProductDisplay.php
www/jana19/cv08/components/SlideDisplay.php
www/jana19/cv08/components/pagination.php
www/jana19/cv08/config/constant.php
www/jana19/cv08/css/styles.css
www/jana19/cv08/db/CategoriesDB.php
www/jana19/cv08/db/Database.php
www/jana19/cv08/db/DatabaseConnection.php
www/jana19/cv08/db/DatabaseOperations.php
www/jana19/cv08/db/ProductsDB.php
www/jana19/cv08/db/SlidesDB.php
www/jana19/cv08/includes/cookies.php
www/jana19/cv08/includes/footer.php
www/jana19/cv08/includes/header.php
www/jana19/cv08/index.html
www/jana19/cv08/index.php
www/jana19/cv08/login.php
www/jana19/cv08/logout.php

https://eso.vse.cz/~jana19/cv08/index.php
odevzdávám alespoň část. Zasekla jsem se na chybě z cart.php - nevím jak to vyřešit. Původně mi to hízelo chybu, teď co jsme koukala na eso mi to chybu nedává (nevím proč). Ale nepovedlo se mi zaznamenávat ty nákupy.

jana19-cv08

---

www/lacp06/cv10/admin-check.php
www/lacp06/cv10/buy.php
www/lacp06/cv10/cart.php
www/lacp06/cv10/create-item.php
www/lacp06/cv10/db/database_eshop.php
www/lacp06/cv10/db/db_eshop.php
www/lacp06/cv10/delete-item.php
www/lacp06/cv10/edit-item.php
www/lacp06/cv10/includes/Footer.php
www/lacp06/cv10/includes/Header.php
www/lacp06/cv10/includes/ProductDisplay.php
www/lacp06/cv10/index.php
www/lacp06/cv10/login.php
www/lacp06/cv10/logout.php
www/lacp06/cv10/manager-check.php
www/lacp06/cv10/registration.php
www/lacp06/cv10/remove-item.php
www/lacp06/cv10/styles.css
www/lacp06/cv10/user-check.php
www/lacp06/cv10/user-privileges.php

Odevzdávám cv10
https://eso.vse.cz/~lacp06/cv10/index.php
user1@gmail.com 12345678 privilegia = 1
user2@gmail.com 12345678 privilegia = 2
user3@gmail.com 12345678 privilegia = 3

lacp06-cv10

---

www/brud06/cv10/admin_required.php
www/brud06/cv10/buy.php
www/brud06/cv10/cart.php
www/brud06/cv10/components/GoodsDisplay.php
www/brud06/cv10/create-item.php
www/brud06/cv10/css/myStyle.css
www/brud06/cv10/css/style.css
www/brud06/cv10/db/GoodsDB.php
www/brud06/cv10/db/UserDB.php
www/brud06/cv10/db/database.php
www/brud06/cv10/delete-item.php
www/brud06/cv10/edit-item.php
www/brud06/cv10/includes/foot.php
www/brud06/cv10/includes/head.php
www/brud06/cv10/index.php
www/brud06/cv10/login.php
www/brud06/cv10/logout.php
www/brud06/cv10/manager_required.php
www/brud06/cv10/registration.php
www/brud06/cv10/remove-item.php
www/brud06/cv10/store.php
www/brud06/cv10/user-privileges.php
www/brud06/cv10/user_required.php

Dobrý den,
odevzdávám domácí úkol LAB10
https://eso.vse.cz/~brud06/cv10/
pikachu@pokemons.cz 12345678 - privilege 3
pikachu@pokemons.czkm 12345678 - privilege 2
pikachu@pokemons.czk 12345678 - privilege 1

brud06-cv10

---

www/mald16/cv10/create-item.php
www/mald16/cv10/db/db.php
www/mald16/cv10/delete-item.php
www/mald16/cv10/edit-item.php
www/mald16/cv10/edit-user-privilege.php
www/mald16/cv10/inc/foot.php
www/mald16/cv10/inc/head.php
www/mald16/cv10/index.php
www/mald16/cv10/logic/allowed-roles.php
www/mald16/cv10/logic/display-errors.php
www/mald16/cv10/logic/require-login.php
www/mald16/cv10/login.php
www/mald16/cv10/logout.php
www/mald16/cv10/registration.php
www/mald16/cv10/user-privileges.php

https://eso.vse.cz/~mald16/cv10/
**Logins:**
user@vse.cz
manager@vse.cz
admin@vse.cz
**Heslo:**
Internet1

mald16-cv10

---

www/adad05/cv10/admin-required-error.php
www/adad05/cv10/admin-required.php
www/adad05/cv10/administration.php
www/adad05/cv10/buy.php
www/adad05/cv10/cart.php
www/adad05/cv10/classes/Database.php
www/adad05/cv10/classes/DatabaseConnection.php
www/adad05/cv10/classes/DatabaseOperations.php
www/adad05/cv10/classes/GoodsDB.php
www/adad05/cv10/classes/Privilege.php
www/adad05/cv10/classes/UsersDB.php
www/adad05/cv10/components/body.php
www/adad05/cv10/components/tabs.php
www/adad05/cv10/create-item.php
www/adad05/cv10/css/styles.css
www/adad05/cv10/delete-item.php
www/adad05/cv10/edit-item.php
www/adad05/cv10/includes/footer.php
www/adad05/cv10/includes/head.php
www/adad05/cv10/index.php
www/adad05/cv10/login.php
www/adad05/cv10/logout.php
www/adad05/cv10/manager-required-error.php
www/adad05/cv10/manager-required.php
www/adad05/cv10/register.php
www/adad05/cv10/remove-item.php

Dobrý večer, odevzdávám úkol 10.
Zde je link na eso: https://eso.vse.cz/~adad05/cv10
Pro vyzkoušení práv přikládám účty a hesla:
['user@shop.cz', '123456789', 'privilege 0']
['manager@shop.cz', '123456789', 'privilege 1']
['admin@shop.cz', '123456789', 'privilege 2']

adad05-cv10

---

www/talp03/cv10/UserDB.php
www/talp03/cv10/admin-required.php
www/talp03/cv10/create-item.php
www/talp03/cv10/index.php
www/talp03/cv10/login.php
www/talp03/cv10/logout.php
www/talp03/cv10/register.php
www/talp03/cv10/remove-item.php
www/talp03/cv10/update-item.php
www/talp03/cv10/user-privileges.php
www/talp03/cv10/users
www/talp03/cv10/utils/database.php

https://eso.vse.cz/~talp03/cv10/

talp03-cv10

---

www/lean04/cv10/auth/adminRequired.php
www/lean04/cv10/auth/logout.php
www/lean04/cv10/auth/managerRequired.php
www/lean04/cv10/auth/registeredUserRequired.php
www/lean04/cv10/cart.php
www/lean04/cv10/components/LoginForm.php
www/lean04/cv10/components/ProductDisplay.php
www/lean04/cv10/components/ProductForm.php
www/lean04/cv10/components/RegistrationForm.php
www/lean04/cv10/create-item.php
www/lean04/cv10/css/bootstrap.css
www/lean04/cv10/css/styles.css
www/lean04/cv10/database/Database.php
www/lean04/cv10/database/ProductsDB.php
www/lean04/cv10/database/UsersDB.php
www/lean04/cv10/edit-item.php
www/lean04/cv10/includes/footer.php
www/lean04/cv10/includes/header.php
www/lean04/cv10/index.php
www/lean04/cv10/login.php
www/lean04/cv10/products/buy.php
www/lean04/cv10/products/delete-item.php
www/lean04/cv10/products/remove-item.php
www/lean04/cv10/register.php
www/lean04/cv10/user-privileges.php
www/lean04/cv10/users/set_privileges.php

Odkaz na práce na serveru eso je https://eso.vse.cz/~lean04/cv10/
User email: bob@bob.bob
Manager email:  mng@mng.mng
Admin email: adm@adm.adm
Heslo: asdfasdf

lean04-cv10

---

www/pycd01/cv10/classes/Users.php
www/pycd01/cv10/create-item.php
www/pycd01/cv10/creds.md
www/pycd01/cv10/delete-item.php
www/pycd01/cv10/edit-item.php
www/pycd01/cv10/incl/footer.php
www/pycd01/cv10/incl/header.php
www/pycd01/cv10/incl/navbar.php
www/pycd01/cv10/index.php
www/pycd01/cv10/login.php
www/pycd01/cv10/logout.php
www/pycd01/cv10/main.php
www/pycd01/cv10/register.php
www/pycd01/cv10/styles/form.css
www/pycd01/cv10/styles/style.css
www/pycd01/cv10/user-privileges.php
www/pycd01/cv10/utils/db.php

**email;name;password;privilege**
a@a.com;Aa Aa;aaa;1
b@b.com;Bb Bb;bbb;1
man@man.com;Man Cc;ccc;2
admin@admin.com;Admin Dd;ddd;3
https://eso.vse.cz/~pycd01/cv10/

pycd01-cv10
